---
- hosts: ios
  gather_facts: yes
  connection: network_cli
  become: yes
  become_method: enable
  ignore_errors: yes

  vars:
    #authentication_provider: normal (tacacs) | local | alternate
    authentication_provider: normal
    # run_type: test | push | both
    run_type: both
    # reeform_type: general | named
    freeform_type: general

  tasks:
  - name: obtain login credentials
    include_vars: auth/secrets.yml

  - name: Set Username and Password
    set_fact:
      remote_user: "{{ creds['username'] }}"
      ansible_ssh_pass: "{{ creds['password'] }}"
    when: authentication_provider == "normal"

  - name: define authentication provider User Local {{ local_creds['username'] }}
    set_fact:
      remote_user: "{{ local_creds['username'] }}"
      ansible_ssh_pass: "{{ local_creds['password'] }}"
    when: authentication_provider == "local"

  - name: define authentication provider Alternate {{ alt_creds['username'] }}
    set_fact:
      remote_user: "{{ alt_creds['username'] }}"
      ansible_ssh_pass: "{{ alt_creds['password'] }}"
    when: authentication_provider == "alternate"

  - name: Gather Facts
    ios_facts:
      gather_subset: all
    register: ios_response

  - name: Hostname for "{{ inventory_hostname }}"
    debug: var=ansible_net_hostname
  
  - name: Version for "{{ inventory_hostname }}"
    debug: var=ansible_net_version

  - name: Test Configuration Lines for {{ inventory_hostname }}
    debug: 
      msg: "{{ lookup('file', './cfg/ios_freeform.cfg') }}"
    when: (run_type == "test") or
          (run_type == "both")

  - name: Load Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
    ios_config:
      backup: yes
      src: cfg/{{ inventory_hostname }}.cfg
      match: none
      save_when : changed
    when: (run_type == "push") or
          (run_type == "both") and 
          (freeform_type == "named") 

  - name: Load Configuration for {{ inventory_hostname }} {{ ansible_date_time.iso8601 }}
    ios_config:
      backup: yes
      src: cfg/ios_freeform.cfg
      match: none
      save_when : changed
    when: (run_type == "push") or
          (run_type == "both") and 
          (freeform_type == "general") 